apiVersion: apps/v1
kind: Deployment
metadata:
  name: gksky-app-github
  labels:
    app: gksky-app
spec:
  selector:
    matchLabels:
        app: gksky-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gksky-app
    spec:
      containers:
        - name: gksky-app
          image: 097084951758.dkr.ecr.us-east-1.amazonaws.com/gksky:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
